steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=cicd/service-account.json.enc
      - --plaintext-file=cicd/service-account.json
      - --location=global
      - --keyring=pbrt
      - --key=pbrt
  - name: 'golang:1.11'
    args: ['go', 'test', '-v', './cmd/...', './pkg/...', ]
  - name: 'golang:1.11'
    args: ['bash', '-c', 'go test -bench=. -benchmem ./cmd/... ./pkg/... > performance_results.out']
  - name: 'gcr.io/i-m-a-g-e-s/go-bench-report:v0.0.3'
    env:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/cicd/service-account.json
    entrypoint: 'sh'
    args: ['-c', 'cat performance_results.out | go-bench-report -p $PROJECT_ID -b $BRANCH_NAME -g $SHORT_SHA -v $(cat VERSION) ']
