// Code generated by MockGen. DO NOT EDIT.
// Source: texture.go

// Package pbrt is a generated GoMock package.
package pbrt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTextureMapping2D is a mock of TextureMapping2D interface
type MockTextureMapping2D struct {
	ctrl     *gomock.Controller
	recorder *MockTextureMapping2DMockRecorder
}

// MockTextureMapping2DMockRecorder is the mock recorder for MockTextureMapping2D
type MockTextureMapping2DMockRecorder struct {
	mock *MockTextureMapping2D
}

// NewMockTextureMapping2D creates a new mock instance
func NewMockTextureMapping2D(ctrl *gomock.Controller) *MockTextureMapping2D {
	mock := &MockTextureMapping2D{ctrl: ctrl}
	mock.recorder = &MockTextureMapping2DMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTextureMapping2D) EXPECT() *MockTextureMapping2DMockRecorder {
	return m.recorder
}

// Map mocks base method
func (m *MockTextureMapping2D) Map(si *SurfaceInteraction) (*Point2f, *Vector2f, *Vector2f) {
	ret := m.ctrl.Call(m, "Map", si)
	ret0, _ := ret[0].(*Point2f)
	ret1, _ := ret[1].(*Vector2f)
	ret2, _ := ret[2].(*Vector2f)
	return ret0, ret1, ret2
}

// Map indicates an expected call of Map
func (mr *MockTextureMapping2DMockRecorder) Map(si interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockTextureMapping2D)(nil).Map), si)
}

// MockSpectrumTexture is a mock of SpectrumTexture interface
type MockSpectrumTexture struct {
	ctrl     *gomock.Controller
	recorder *MockSpectrumTextureMockRecorder
}

// MockSpectrumTextureMockRecorder is the mock recorder for MockSpectrumTexture
type MockSpectrumTextureMockRecorder struct {
	mock *MockSpectrumTexture
}

// NewMockSpectrumTexture creates a new mock instance
func NewMockSpectrumTexture(ctrl *gomock.Controller) *MockSpectrumTexture {
	mock := &MockSpectrumTexture{ctrl: ctrl}
	mock.recorder = &MockSpectrumTextureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSpectrumTexture) EXPECT() *MockSpectrumTextureMockRecorder {
	return m.recorder
}

// Evaluate mocks base method
func (m *MockSpectrumTexture) Evaluate(si *SurfaceInteraction) Spectrum {
	ret := m.ctrl.Call(m, "Evaluate", si)
	ret0, _ := ret[0].(Spectrum)
	return ret0
}

// Evaluate indicates an expected call of Evaluate
func (mr *MockSpectrumTextureMockRecorder) Evaluate(si interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockSpectrumTexture)(nil).Evaluate), si)
}

// MockFloatTexture is a mock of FloatTexture interface
type MockFloatTexture struct {
	ctrl     *gomock.Controller
	recorder *MockFloatTextureMockRecorder
}

// MockFloatTextureMockRecorder is the mock recorder for MockFloatTexture
type MockFloatTextureMockRecorder struct {
	mock *MockFloatTexture
}

// NewMockFloatTexture creates a new mock instance
func NewMockFloatTexture(ctrl *gomock.Controller) *MockFloatTexture {
	mock := &MockFloatTexture{ctrl: ctrl}
	mock.recorder = &MockFloatTextureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFloatTexture) EXPECT() *MockFloatTextureMockRecorder {
	return m.recorder
}

// Evaluate mocks base method
func (m *MockFloatTexture) Evaluate(si *SurfaceInteraction) float64 {
	ret := m.ctrl.Call(m, "Evaluate", si)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Evaluate indicates an expected call of Evaluate
func (mr *MockFloatTextureMockRecorder) Evaluate(si interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFloatTexture)(nil).Evaluate), si)
}
